# Generated by Django 5.0.7 on 2024-08-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_task_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
